### PR TITLE
add placeholder.js

### PR DESCRIPTION
**Pull request by hustcc**
request to add reposl: 
 - [https://github.com/hustcc/placeholder.js](https://github.com/hustcc/placeholder.js)
 - [https://github.com/hustcc/GitHub-Repo-Widget.js](https://github.com/hustcc/GitHub-Repo-Widget.js)

very thx.

### CODE REVIEW

**Comment by sbrl** [comment]
I get a 404 on those links. Are you sure they are correct?

**Comment by hustcc** [comment]
very sorry, my all project has been deleted because of some reason. ignore it pls, very sorry.

**Comment by sbrl** [comment]
Please could you close the pull request? You could submit another one once it's sorted out if you wanted.

**Comment by hustcc** [comment]
ok

**Pull request closed without merging**
