### PR TITLE
Added TinyAnimate

### PR DESCRIPTION
**Pull request by branneman**
TinyAnimate: https://github.com/branneman/TinyAnimate

I can rebase if other PR's are merged first and my PR is out of date, just let me know in the comments.

### CODE REVIEW

**Comment by sbrl** [comment]
_Selected for inclusion in a commit bundle._

**Comment by sbrl** [comment]
Hello @branneman, I've selected your PR for inclusion in a commit bundle, but I've just noticed that your repo doesn't use the MIT license or a similarly permissive license - this is one of the guidelines for adding add library to microjs.com.

Is it possible to correct this please?

Thanks.

**Comment by branneman** [comment]
The license actually already was MIT, as you can see here:
https://github.com/branneman/TinyAnimate/blob/master/package.json#L16

But since it wasn't that obvious, I've just added commit [b502f42](https://github.com/branneman/TinyAnimate/commit/b502f422e532c214f2a054dd97391fa404432aeb), adding a license file and section in the readme.

**Comment by sbrl** [comment]
Thanks! I must not have noticed that.

I'll send off my commit bundle off as soon as I've finished preparing it then.

**Pull request merged**
