### PR TITLE
Added NodeList.js

### PR DESCRIPTION
**Pull request by eorroe**

### CODE REVIEW

**Comment by sbrl** [comment]
_Selected for inclusion in a commit bundle._

**Comment by sbrl** [comment]
Hello @eorroe,

I've added your PR to my commit bundle, but I've just noticed that your repo doesn't have a license. All libraries added to microjs.com must have license equal or similar the MIT license.

Is it possible to fix this please?

--Starbeamrainbowlabs

**Comment by eorroe** [comment]
@sbrl DONE!! https://github.com/eorroe/NodeList.js/blob/master/LICENSE

**Comment by sbrl** [comment]
@eorroe Awesome, thanks!

That just leaves the author of TinyAnimate.js, and then I can submit this commit bundle.

**Comment by eorroe** [comment]
Perfect, thanks for making it easy to submit micro libraries, and love the site :+1:

**Pull request merged**
