### PR TITLE
Added razax.js to the list

### PR DESCRIPTION
**Pull request by razaibi**
Added new lib

### CODE REVIEW

**Comment by sbrl** [comment]
Please could you point the `source` url to the _unminified_ source code.

**Comment by razaibi** [comment]
Yes, I have updated the repository to include both the minified and unminified source code. Here is the link to the unminified code:

https://github.com/razaibi/razaxjs/blob/master/razax.js

**Comment by sbrl** [comment]
Sorry, I meant that the `source` link in data.js should link to the unminified source, not the minified source.

e.g.

```
...
    source: "https://raw.githubusercontent.com/razaibi/razaxjs/master/razax.js"
...
```

not


```
...
    source: "https://raw.githubusercontent.com/razaibi/razaxjs/master/razax.min.js"
...
```

The build script automatically minifies your code.

**Comment by razaibi** [comment]
I have made the change to my branch. Will I be required to create a new pull request?

**Comment by sbrl** [comment]
Nope, this PR should be updated automatically if you push to the same branch that you made the pull request with. If you don't see any more commits under this pull request, then you haven't done it right.

**Comment by razaibi** [comment]
Alright, thanks, I guess now it is fine, I can see the latest commit.

**Comment by sbrl** [comment]
Awesome. Could you squash your commits down into a single commit too please?

**Comment by razaibi** [comment]
Apologize for the inconvenience , I am not too well versed with the Git prompt and the client on my windows machine isnt helping either. Is there a way I could squash it from the web application here?

**Comment by sbrl** [comment]
Nope, but I can give you a guide on how to do it though the command prompt: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

According to the above guide you want something like `git rebase -i HEAD~3`.

If you are having problems I'm happy to help.

**Comment by razaibi** [comment]
yes!! done.  All commits merged into one. Thanks for the help.

**Comment by razaibi** [comment]
is this fine now to be included in your list?

**Comment by sbrl** [comment]
Thanks for reminding me. Yes it is - I've added it to a new commit bundle. It'll appear as a PR soon.

**Pull request merged**
