### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by DylanPiercey**
Added FrenchPress MVC/Template engine.

### CODE REVIEW

**Comment by r4j4h** [comment]
https://github.com/DylanPiercey/FrenchPress gives me a 404 now

**Comment by sbrl** [comment]
If the repo link gives a 404, then I vote to close this PR.

**Comment by DylanPiercey** [comment]
Sorry, the project has been re-branded and isn't re-released yet. Thanks

**Comment by r4j4h** [comment]
No worries, I look forward to the future PR after that process is finished =)

**Pull request closed without merging**
