### PR TITLE
added viiny-dragger

### PR DESCRIPTION
**Pull request by giraysam**

### CODE REVIEW

**Comment by sbrl** [comment]
Could you link to change the `source` url to point to your unminified source and not the releases page please? That link is used by the build script to automatically minify and check your code.

**Comment by giraysam** [comment]
i changed source link.

**Comment by sbrl** [comment]
Thanks! Finally, could you squash all your commits together into one please?

**Comment by giraysam** [comment]
ok i have done.

**Comment by giraysam** [comment]
i have changed source link with raw link.

**Comment by sbrl** [comment]
@giraysam Thanks! I've included your library in my latest commit bundle. It's PR #800.

**Pull request closed without merging**
